<a href="https://colab.research.google.com/github/singhbhupender1/ML-notebooks/blob/master/Image_data_channel_formats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Images as 3D Arrays

**Typically, the image format has one dimension for rows (height), one for columns (width) and one for channels.**

**If the image is black and white (grayscale), the channels dimension may not be explicitly present, e.g. there is one unsigned integer pixel value for each (row, column) coordinate in the image.**

**Colored images typically have three channels, for the pixel value at the (row, column) coordinate for the red, green, and blue components.**

**Deep learning neural networks require that image data be provided as three-dimensional arrays.**

**There are two ways to represent the image data as a three dimensional array. The first involves having the channels as the last or third dimension in the array. This is called “channels last“. The second involves having the channels as the first dimension in the array, called “channels first“.**

**Channels *Last*. Image data is represented in a three-dimensional array where the last channel represents the color channels, e.g. [rows][cols][channels].**

**Channels *First*. Image data is represented in a three-dimensional array where the first channel represents the color channels, e.g. [channels][rows][cols].**

##Manipulating Image Channels

**You may need to change or manipulate the image channels or channel ordering.**

**This can be achieved easily using the NumPy python library.**

##How to Add a Channel to a Grayscale Image

**Grayscale images are loaded as a two-dimensional array.**

**Before they can be used for modeling, you may have to add an explicit channel dimension to the image. This does not add new data; instead, it changes the array data structure to have an additional third axis with one dimension to hold the grayscale pixel values.**

**For example, a grayscale image with the dimensions [rows][cols] can be changed to [rows][cols][channels] or [channels][rows][cols] where the new [channels] axis has one dimension.**

**This can be achieved using the *expand_dims*() NumPy function. The “axis” argument allows you to specify where the new dimension will be added to the first, e.g. first for channels first or last for channels last.**

In [1]:
!pip install pillow

In [5]:
#example of expanding dimensions
from numpy import expand_dims
from numpy import asarray
from PIL import Image
from urllib.request import urlopen
#load the image
url = 'https://3qeqpr26caki16dnhd19sv6by6v-wpengine.netdna-ssl.com/wp-content/uploads/2019/01/penguin_arade.jpg'
img = Image.open('/content/penguin_arade.jpg')
#convert the image to grayscale
img = img.convert(mode='L')
#convert to numpy array
data = asarray(img)
print(data.shape)
#add channels first
data_first = expand_dims(data, axis=0)
print(data_first.shape)
#add channels last
data_last = expand_dims(data, axis=2)
print(data_last.shape)

(424, 640)
(1, 424, 640)
(424, 640, 1)


**Another popular alternative to expanding the dimensions of an array is to use the reshape() NumPy function and specify a tuple with the new shape; for example:**



```
data = data.reshape((424, 640, 1))
```



##How to Change Image Channel Ordering

**After a color image is loaded as a three-dimensional array, the channel ordering can be changed.**

**This can be achieved using the *moveaxis*() NumPy function. It allows you to specify the index of the source axis and the destination axis.**

**This function can be used to change an array in channel last format such, as [rows][cols][channels] to channels first format, such as [channels][rows][cols], or the reverse.**

In [7]:
#change image from channels last to channels first format
from numpy import moveaxis
from numpy import asarray
from PIL import Image
#load the color image
img = Image.open('/content/penguin_arade.jpg')
#convert to numpy array
data = asarray(img)
print(data.shape)
#change channels last to channels first format
data = moveaxis(data, 2, 0)
print(data.shape)
#change channels first to channls last format
data = moveaxis(data, 0, 2)
print(data.shape)

(424, 640, 3)
(3, 424, 640)
(424, 640, 3)


**The moveaxis() function is then used to move the channels axis from position 2 to position 0 and the result is confirmed showing channels first format (3, 424, 640). This is then reversed, moving the channels in position 0 to position 2 again.**

##Keras Channel Ordering

**Keras wraps a number of mathematical libraries, and each has a preferred channel ordering. The three main libraries that Keras may wrap and their preferred channel ordering are listed below:**

**TensorFlow: Channels last order.**

**Theano: Channels first order.**

**CNTK: Channels last order.**

##Default Channel Ordering

**The library and preferred channel ordering are listed in the Keras configuration file, stored in your home directory under ~/.keras/keras.json.**

**The preferred channel ordering is stored in the “image_data_format” configuration setting and can be set as either “channels_last” or “channels_first“.**



```

{
    "image_data_format": "channels_last",
    "backend": "tensorflow",
    "epsilon": 1e-07,
    "floatx": "float32"
}
```



**Based on your preferred channel ordering, you will have to prepare your image data to match the preferred ordering.**

**Specifically, this will include tasks such as:**

**Resizing or expanding the dimensions of any training, validation, and test data to meet the expectation.**

**Specifying the expected input shape of samples when defining models (e.g. input_shape=(28, 28, 1)).**

##Model-Specific Channel Ordering

**In addition, those neural network layers that are designed to work with images, such as Conv2D, also provide an argument called “data_format” that allows you to specify the channel ordering**



```
model.add(Conv2D(..., data_format='channels_first'))
```



**By default, this will use the preferred ordering specified in the “image_data_format” value of the Keras configuration file. Nevertheless, you can change the channel order for a given model, and in turn, the datasets and input shape would also have to be changed to use the new channel ordering for the model.**

##Query Channel Ordering


**You can confirm your current preferred channel ordering by printing the result of the image_data_format() function. The example below demonstrates.**



```
# show preferred channel order
from keras import backend
print(backend.image_data_format())
```



#Force Channel Ordering

** the channel ordering can be forced for a specific program.**

**This can be achieved by calling the *set_image_data_format*() function on the Keras backend to either *‘channels_first‘* (theano) for channel-first ordering, or ‘channels_last‘ (tensorflow) for channel-last ordering.**

**This can be useful if you want a program or model to operate consistently regardless of Keras default channel ordering configuration.**

In [9]:
#force a channel ordering
from keras import backend
#force channels-first ordering
backend.set_image_data_format('channels_first')
print(backend.image_data_format())
#force channels-last ordering
backend.set_image_data_format('channels_last')
print(backend.image_data_format())

channels_first
channels_last
